In [4]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [6]:
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

engine = engine = create_engine('postgresql://live_crimehtx:%7C_IVE_C%7C3IME_hTX001@crimehtxdb.c0fjj9b9p4wl.us-east-1.rds.amazonaws.com/crimehtxdb')
Base = declarative_base(bind=engine)
Session = sessionmaker(bind=engine)Select * from crime09_15 limit 10
session = Session()

conn = session.bind

In [7]:
# with engine.connect() as con:

#     rs = con.execute('SELECT * FROM book')

#     for row in rs:
#         print row

In [8]:
# test x : -95.322341
# test y : 29.800429
df = pd.read_sql_query('Select * from crime09_15 limit 10', engine)

In [9]:
df

,x,y,address,city,state,date,hour,offensetype,beats,blockrange,...,area_sq_mi,perimet_mi,shape_leng,perimeter,polyid,snbname,year,month,day,weekday
0,-95.322341,29.801320,4500 WIPPRECHT ST,HOUSTON,TX,1980-05-01,12.0,Aggravated Assault,7C20,4500-4599,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,1980.0,5.0,1.0,3.0
1,-95.331480,29.803852,4800 SAYERS ST,HOUSTON,TX,2006-08-06,22.0,Auto Theft,7C20,4800-4899,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2006.0,8.0,6.0,6.0
2,-95.327130,29.800429,4400 LOS ANGELES ST,HOUSTON,TX,2009-07-28,9.0,Auto Theft,7C20,4400-4499,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,7.0,28.0,1.0
3,-95.303058,29.807684,6300 NORTH LP E,HOUSTON,TX,2009-07-31,17.0,Burglary,7C20,6300-6399,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,7.0,31.0,4.0
4,-95.326951,29.796888,4300 CRANE ST,HOUSTON,TX,2009-08-02,6.0,Theft,7C20,4300-4399,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,2.0,6.0
5,-95.306603,29.797050,6300 CRANE ST,HOUSTON,TX,2009-08-03,6.0,Aggravated Assault,7C20,6300-6399,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,3.0,0.0
6,-95.322282,29.797828,4100 WIPPRECHT ST,HOUSTON,TX,2009-08-03,22.0,Burglary,7C20,4100-4199,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,3.0,0.0
7,-95.316860,29.795118,3800 LOCKWOOD DR,HOUSTON,TX,2009-08-04,14.0,Robbery,7C20,3800-3899,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,4.0,1.0
8,-95.316910,29.797056,4000 LOCKWOOD DR,HOUSTON,TX,2009-08-04,10.0,Aggravated Assault,7C20,4000-4099,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,4.0,1.0
9,-95.317071,29.811072,5500 LOCKWOOD DR,HOUSTON,TX,2009-08-05,6.0,Theft,7C20,5500-5599,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,5.0,2.0

In [10]:
df = pd.read_sql_query('Select * from crime09_15', engine)

In [11]:
df.head()

,x,y,address,city,state,date,hour,offensetype,beats,blockrange,...,area_sq_mi,perimet_mi,shape_leng,perimeter,polyid,snbname,year,month,day,weekday
0,-95.322341,29.801320,4500 WIPPRECHT ST,HOUSTON,TX,1980-05-01,12.0,Aggravated Assault,7C20,4500-4599,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,1980.0,5.0,1.0,3.0
1,-95.331480,29.803852,4800 SAYERS ST,HOUSTON,TX,2006-08-06,22.0,Auto Theft,7C20,4800-4899,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2006.0,8.0,6.0,6.0
2,-95.327130,29.800429,4400 LOS ANGELES ST,HOUSTON,TX,2009-07-28,9.0,Auto Theft,7C20,4400-4499,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,7.0,28.0,1.0
3,-95.303058,29.807684,6300 NORTH LP E,HOUSTON,TX,2009-07-31,17.0,Burglary,7C20,6300-6399,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,7.0,31.0,4.0
4,-95.326951,29.796888,4300 CRANE ST,HOUSTON,TX,2009-08-02,6.0,Theft,7C20,4300-4399,...,7.085752,11.097944,58597.143714,52352.042,52.0,KASHMERE GARDENS,2009.0,8.0,2.0,6.0

In [21]:
df.offensetype.value_counts()

Theft                 281722
Burglary              100994
Auto Theft             54161
Robbery                41964
Aggravated Assault     41523
Rape                    3193
Murder                  1030
1                          6
Name: offensetype, dtype: int64

In [24]:
df.snbname.value_counts()

ALIEF                                          28118
SHARPSTOWN                                     23941
GREATER GREENSPOINT                            22228
NORTHSIDE/NORTHLINE                            19726
MID WEST                                       19458
GREATER UPTOWN                                 19365
GOLFCREST / BELLFORT / REVEILLE                17373
SOUTH BELT / ELLINGTON                         13212
BRIAR FOREST                                   11752
BRAYS OAKS                                     11572
ELDRIDGE / WEST OAKS                           11426
GREENWAY / UPPER KIRBY AREA                    10519
DOWNTOWN                                       10497
NORTHSHORE                                     10341
WASHINGTON AVENUE COALITION / MEMORIAL PARK    10042
SPRING BRANCH WEST                              9797
WESTWOOD                                        9185
FAIRBANKS / NORTHWEST CROSSING                  8683
MEMORIAL                                        8557
CENTRAL NORTHWEST                               8413
EASTEX - JENSEN AREA                            8058
WESTCHASE                                       7958
MIDTOWN                                         7726
CENTRAL SOUTHWEST                               7586
SUNNYSIDE                                       7407
NEARTOWN - MONTROSE                             7134
GREATER INWOOD                                  7050
GREATER HOBBY AREA                              6896
SPRING BRANCH EAST                              6821
EAST HOUSTON                                    6801
                                               ...
BRAEBURN                                        3132
LAZYBROOK / TIMBERGROVE                         3122
EDGEBROOK AREA                                  3080
KASHMERE GARDENS                                2968
IAH / AIRPORT AREA                              2741
ADDICKS PARK TEN                                2722
WILLOW MEADOWS / WILLOWBEND AREA                2430
PARK PLACE                                      2201
MINNETEX                                        2125
PECAN PARK                                      1980
CARVERDALE                                      1972
SECOND WARD                                     1810
DENVER HARBOR / PORT HOUSTON                    1703
MEDICAL CENTER AREA                             1662
INDEPENDENCE HEIGHTS                            1571
GREATER EASTWOOD                                1391
MUSEUM PARK                                     1342
FOURTH WARD                                     1118
HIDDEN VALLEY                                    981
LAWNDALE / WAYSIDE                               968
LANGWOOD                                         577
WESTBRANCH                                       573
HARRISBURG / MANCHESTER                          564
SETTEGAST                                        554
PLEASANTVILLE AREA                               507
EL DORADO / OATES PRAIRIE                        478
FONDREN GARDENS                                  477
CLINTON PARK TRI-COMMUNITY                       372
HUNTERWOOD                                       294
LAKE HOUSTON                                     134
Name: snbname, Length: 87, dtype: int64